name: delta
description: An adaptable Flutter library, empowering developers with utilities, screen adaptation, conversions, Area methods, global date formats, and country data.
version: 0.0.4

homepage: https://github.com/Mehrankhan-METRA-RGB/delta_flutter/blob/master/README.md
repository: https://github.com/Mehrankhan-METRA-RGB/delta_flutter
issue_tracker: https://github.com/Mehrankhan-METRA-RGB/delta_flutter/issues
documentation: https://delta.metra.dev
license: MIT
environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  vm_service: ^11.10.0
  http: ^1.1.0

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


